/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;

/**
 *
 * @author Jhon
 */
public class entradaSalidaPanel extends javax.swing.JPanel {

    /**
     * Creates new form entradaSalidaPanel
     */
    vistaPrincipal frame; // instancia frame del frame principal
    public entradaSalidaPanel(vistaPrincipal frame) {
        this.frame = frame; // la instancia del frame principal la paso a una instancia en esta clase para poder usar los metodos del frame principal
        initComponents();
        setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        btnVolverESInventario = new javax.swing.JButton();

        labelTitulo.setText("ENTRADA Y SALIDA DE INVENTARIO");

        btnVolverESInventario.setText("Volver");
        btnVolverESInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverESInventarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVolverESInventario)
                    .addComponent(labelTitulo))
                .addContainerGap(688, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(labelTitulo)
                .addGap(27, 27, 27)
                .addComponent(btnVolverESInventario)
                .addContainerGap(553, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverESInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverESInventarioActionPerformed
        // TODO add your handling code here:
        frame.swap(0); // hace el llamado al panel de opciones
    }//GEN-LAST:event_btnVolverESInventarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolverESInventario;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
