/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import logica.RegistroGastoLogica;
import modelo.Registrogastos;
import modelo.Registroingresos;

/**
 *
 * @author Usuario
 */
public class registroGastoPanel extends javax.swing.JPanel {

    /**
     * Creates new form registroGastoPanel
     */
    vistaPrincipal frame; // instancia frame del frame principal 
    DefaultTableModel modelo;
    private Registrogastos registroGastos;
    private RegistroGastoLogica registroGastoLogica;
    private List<Registrogastos> listaRegistroGastos;
    public registroGastoPanel(vistaPrincipal frame) {
        this.frame = frame; // la instancia del frame principal la paso a una instancia en esta clase para poder usar los metodos del frame principal
        listaRegistroGastos = new ArrayList<Registrogastos>();
        registroGastos = new Registrogastos(); 
        RegistroGastoLogica registroGastoLogica = new RegistroGastoLogica();
        
        initComponents();
        setBackground(Color.white);
        ComboBoxMes.removeAllItems();
        ComboBoxMes.addItem("ENERO");
        ComboBoxMes.addItem("FEBRERO");
        ComboBoxMes.addItem("MARZO");
        ComboBoxMes.addItem("ABRIL");
        ComboBoxMes.addItem("MAYO");
        ComboBoxMes.addItem("JUNIO");
        ComboBoxMes.addItem("JULIO");
        ComboBoxMes.addItem("AGOSTO");
        ComboBoxMes.addItem("SEPTIEMBRE");
        ComboBoxMes.addItem("OCTUBRE");
        ComboBoxMes.addItem("NOVIEMBRE");
        ComboBoxMes.addItem("DICIEMBRE");
        
        listaRegistroGastos = registroGastoLogica.listarRegistrosIngresos();
        llenarTablaGastos(listaRegistroGastos);
    }
    
    public void llenarTablaGastos(List<Registrogastos> reggastos){
        
        List<Registrogastos> lista;
        lista = reggastos;
        setTabla(lista);
    }
    
    public void setTabla(List<Registrogastos> reggastos){
        modelo =  (DefaultTableModel) tableGastos.getModel();
        
        int size = modelo.getRowCount();
        for(int i=0; i < size; i++){
            modelo.removeRow(0);
        }
        String aux[];
        for(int j=0;j< reggastos.size();j++){
            aux = new String[8];
            
            aux[0] = String.valueOf(reggastos.get(j).getAnioreg())+"-"+String.valueOf(reggastos.get(j).getMesreg())+"-"+String.valueOf(reggastos.get(j).getDiareg());
            aux[1] = "G-"+String.valueOf(reggastos.get(j).getNumregistro());
            aux[2] = reggastos.get(j).getNumidentificacion();
            aux[3] = reggastos.get(j).getNomtercero();
            aux[4] = reggastos.get(j).getCentrodecostos();
            aux[5] = reggastos.get(j).getCuentapuc();
            aux[6] = reggastos.get(j).getObservacion();
            aux[7] = "$ "+String.valueOf(reggastos.get(j).getValor());
            modelo.addRow(aux);
        }
    }
    
    public void setCampoPucSelectGasto(String codigopuc,String nombre){
        txtCuentaPUC.setText(codigopuc+"-"+nombre);
    }
    
    public void setCampoTerceroSelectGasto(int id,String cconit,String nombre){
        txtConsultarTercero.setText(id+"-"+nombre+"-"+cconit);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        btnVolverRegistroGasto = new javax.swing.JButton();
        labelFechaRegistro = new javax.swing.JLabel();
        labelDia = new javax.swing.JLabel();
        txtDia = new javax.swing.JTextField();
        labelMes = new javax.swing.JLabel();
        txtAnio = new javax.swing.JTextField();
        ComboBoxMes = new javax.swing.JComboBox<>();
        labelAnio = new javax.swing.JLabel();
        labelCentroCosto = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnConsultarCentroCosto = new javax.swing.JButton();
        labelCuentaPUC = new javax.swing.JLabel();
        txtCuentaPUC = new javax.swing.JTextField();
        btnConsultarPUC = new javax.swing.JButton();
        labelIDTercero = new javax.swing.JLabel();
        txtConsultarTercero = new javax.swing.JTextField();
        btnConsultarTercero = new javax.swing.JButton();
        labelObservaciones = new javax.swing.JLabel();
        txtObservaciones = new javax.swing.JTextField();
        labelValor = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableGastos = new javax.swing.JTable();
        btnRegistro = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        labelTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelTitulo.setText("REGISTROS DE GASTOS");

        btnVolverRegistroGasto.setText("Volver");
        btnVolverRegistroGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverRegistroGastoActionPerformed(evt);
            }
        });

        labelFechaRegistro.setText("Fecha de Registro: ");

        labelDia.setText("Dia:");

        labelMes.setText("Mes:");

        ComboBoxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        labelAnio.setText("Año:");

        labelCentroCosto.setText("Centro de Costos:");

        btnConsultarCentroCosto.setText("Consultar Centro Costo");

        labelCuentaPUC.setText("Cuenta PUC:");

        btnConsultarPUC.setText("Consultar PUC");
        btnConsultarPUC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarPUCActionPerformed(evt);
            }
        });

        labelIDTercero.setText("ID Tercero:");

        btnConsultarTercero.setText("Consultar Tercero");
        btnConsultarTercero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarTerceroActionPerformed(evt);
            }
        });

        labelObservaciones.setText("Observaciones:");

        labelValor.setText("Valor: ");

        tableGastos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "N° Registro", "N° Identificacion", "Nombre", "Centro Costos", "Cuenta PUC", "Observaciones", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableGastos);

        btnRegistro.setText("Registro");

        btnConsultar.setText("Consultar");

        jButton1.setText("Modificar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnVolverRegistroGasto)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTitulo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelCentroCosto)
                                    .addComponent(labelFechaRegistro)
                                    .addComponent(labelObservaciones)
                                    .addComponent(btnRegistro)
                                    .addComponent(labelIDTercero))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(labelDia)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelMes)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)
                                        .addComponent(labelAnio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(labelValor)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(btnConsultarCentroCosto))
                                                    .addComponent(txtConsultarTercero))
                                                .addGap(22, 22, 22)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnConsultarTercero)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(labelCuentaPUC)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtCuentaPUC, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(btnConsultarPUC))))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(btnConsultar)
                                        .addGap(31, 31, 31)
                                        .addComponent(jButton1))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(labelTitulo)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFechaRegistro)
                    .addComponent(labelDia)
                    .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMes)
                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAnio))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCentroCosto)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarCentroCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCuentaPUC)
                    .addComponent(txtCuentaPUC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarPUC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIDTercero)
                    .addComponent(txtConsultarTercero, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarTercero, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelObservaciones)
                    .addComponent(txtObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelValor)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVolverRegistroGasto)
                .addContainerGap(178, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverRegistroGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverRegistroGastoActionPerformed
        // TODO add your handling code here:
        frame.swap(0); // hace el llamado al panel de opciones
    }//GEN-LAST:event_btnVolverRegistroGastoActionPerformed

    private void btnConsultarPUCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPUCActionPerformed
        // TODO add your handling code here:
        frame.swap(14); // hace el llamado al panel de consultar y seleccionar una cuenta PUC para gasto
    }//GEN-LAST:event_btnConsultarPUCActionPerformed

    private void btnConsultarTerceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarTerceroActionPerformed
        // TODO add your handling code here:
        frame.swap(17); // hace el llamado al panel de consultar y seleccionar un tercero para gasto
    }//GEN-LAST:event_btnConsultarTerceroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxMes;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnConsultarCentroCosto;
    private javax.swing.JButton btnConsultarPUC;
    private javax.swing.JButton btnConsultarTercero;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JButton btnVolverRegistroGasto;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelAnio;
    private javax.swing.JLabel labelCentroCosto;
    private javax.swing.JLabel labelCuentaPUC;
    private javax.swing.JLabel labelDia;
    private javax.swing.JLabel labelFechaRegistro;
    private javax.swing.JLabel labelIDTercero;
    private javax.swing.JLabel labelMes;
    private javax.swing.JLabel labelObservaciones;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelValor;
    private javax.swing.JTable tableGastos;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtConsultarTercero;
    private javax.swing.JTextField txtCuentaPUC;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtObservaciones;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
