/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import logica.RegistroIngresoLogica;
import modelo.Puc;
import modelo.Registroingresos;

/**
 *
 * @author Jhon
 */
public class registroIngresoPanel extends javax.swing.JPanel {

    /**
     * Creates new form registroIngresoPanel
     */
    vistaPrincipal frame; // instancia frame del frame principal
    DefaultTableModel modelo;
    private Puc puc;
    private Registroingresos registroingresos;
    private RegistroIngresoLogica registroingresoLogica;
    private List<Registroingresos> listaRegistroIngresos;
    public registroIngresoPanel(vistaPrincipal frame) {
        this.frame = frame; // la instancia del frame principal la paso a una instancia en esta clase para poder usar los metodos del frame principal
        listaRegistroIngresos = new ArrayList<Registroingresos>();
        registroingresos = new Registroingresos(); 
        RegistroIngresoLogica registroingresoLogica = new RegistroIngresoLogica();
        
        
        
        initComponents();
        setBackground(Color.white);
   
        ComboBoxMes.removeAllItems();
        ComboBoxMes.addItem("ENERO");
        ComboBoxMes.addItem("FEBRERO");
        ComboBoxMes.addItem("MARZO");
        ComboBoxMes.addItem("ABRIL");
        ComboBoxMes.addItem("MAYO");
        ComboBoxMes.addItem("JUNIO");
        ComboBoxMes.addItem("JULIO");
        ComboBoxMes.addItem("AGOSTO");
        ComboBoxMes.addItem("SEPTIEMBRE");
        ComboBoxMes.addItem("OCTUBRE");
        ComboBoxMes.addItem("NOVIEMBRE");
        ComboBoxMes.addItem("DICIEMBRE");
        txtCodigoKardex.setText("0000");
        
        listaRegistroIngresos = registroingresoLogica.listarRegistrosIngresos();
        llenarTablaIngresos(listaRegistroIngresos);
    }
    
    public void llenarTablaIngresos(List<Registroingresos> regingresos){
        
        List<Registroingresos> lista;
        lista = regingresos;
        setTabla(lista);
    }
    
    public void setTabla(List<Registroingresos> regingresos){
        modelo =  (DefaultTableModel) tableRegistroIngreso.getModel();
        
        int size = modelo.getRowCount();
        for(int i=0; i < size; i++){
            modelo.removeRow(0);
        }
        String aux[];
        for(int j=0;j< regingresos.size();j++){
            aux = new String[8];
            
            aux[0] = String.valueOf(regingresos.get(j).getAnioreg())+"-"+String.valueOf(regingresos.get(j).getMesreg())+"-"+String.valueOf(regingresos.get(j).getDiareg());
            aux[1] = "I-"+String.valueOf(regingresos.get(j).getNumregistro());
            aux[2] = regingresos.get(j).getNumidentificacion();
            aux[3] = regingresos.get(j).getNomtercero();
            aux[4] = regingresos.get(j).getCuentapuc();
            aux[5] = regingresos.get(j).getCodigokardex();
            aux[6] = regingresos.get(j).getObservacion();
            aux[7] = "$ "+String.valueOf(regingresos.get(j).getValor());
            modelo.addRow(aux);
        }
    }
    
    public void setCampoPucSelectIngreso(String codigopuc,String nombre){
        txtCuentaPuc.setText(codigopuc+"-"+nombre);
    }
    
    public void setCampoTerceroSelectIngreso(int id,String cconit,String nombre){
        txtNumIdenTercero.setText(id+"-"+nombre+"-"+cconit);
    }
    
    public void setCampoKardexMICSelectIngreso(String codigoMIC,String descripcion){
        txtCodigoKardex.setText(codigoMIC+"-"+descripcion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        btnVolverRegistroIngreso = new javax.swing.JButton();
        labelCuantaPuc = new javax.swing.JLabel();
        txtCuentaPuc = new javax.swing.JTextField();
        labelFechaRegistro = new javax.swing.JLabel();
        labelDia = new javax.swing.JLabel();
        labelMes = new javax.swing.JLabel();
        ComboBoxMes = new javax.swing.JComboBox<>();
        labelAnio = new javax.swing.JLabel();
        txtAnio = new javax.swing.JTextField();
        btnVerCodPuc = new javax.swing.JButton();
        labelCodigoKardex = new javax.swing.JLabel();
        txtCodigoKardex = new javax.swing.JTextField();
        btnConsultarCodigoKardex = new javax.swing.JButton();
        labelObservacion = new javax.swing.JLabel();
        txtObservaciones = new javax.swing.JTextField();
        labelValor = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRegistroIngreso = new javax.swing.JTable();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        labelNumIdenTercereo = new javax.swing.JLabel();
        txtNumIdenTercero = new javax.swing.JTextField();
        btnConsultarTercero = new javax.swing.JButton();
        txtDia = new javax.swing.JTextField();

        labelTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelTitulo.setText("REGISTRO DE INGRESOS");

        btnVolverRegistroIngreso.setText("Volver");
        btnVolverRegistroIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverRegistroIngresoActionPerformed(evt);
            }
        });

        labelCuantaPuc.setText("Cuenta PUC:");

        labelFechaRegistro.setText("Fecha de Registro:");

        labelDia.setText("Dia:");

        labelMes.setText("Mes:");

        ComboBoxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        labelAnio.setText("Año:");

        btnVerCodPuc.setText("Consultar PUC");
        btnVerCodPuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCodPucActionPerformed(evt);
            }
        });

        labelCodigoKardex.setText("Codigo Kardex:");

        btnConsultarCodigoKardex.setText("Consultar Kardex");
        btnConsultarCodigoKardex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarCodigoKardexActionPerformed(evt);
            }
        });

        labelObservacion.setText("Observaciones: ");

        labelValor.setText("Valor: ");

        tableRegistroIngreso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "N° Registro", "N° Identificacion", "Nombre", "Cuenta PUC", "Codigo Kardex", "Observacion", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableRegistroIngreso);

        btnRegistrar.setText("Registrar");

        btnModificar.setText("Modificar");

        btnConsultar.setText("Consultar");

        labelNumIdenTercereo.setText("ID Tercero:");

        btnConsultarTercero.setText("Consultar Tercero");
        btnConsultarTercero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarTerceroActionPerformed(evt);
            }
        });

        txtDia.setPreferredSize(new java.awt.Dimension(50, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnVolverRegistroIngreso)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 75, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTitulo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelCuantaPuc)
                                    .addComponent(labelFechaRegistro)
                                    .addComponent(labelNumIdenTercereo)
                                    .addComponent(labelObservacion)
                                    .addComponent(btnRegistrar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelDia)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelMes)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelAnio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCuentaPuc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnVerCodPuc)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelCodigoKardex)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCodigoKardex, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnConsultarCodigoKardex))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtNumIdenTercero, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnConsultarTercero))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelValor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnConsultar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnModificar)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(labelTitulo)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFechaRegistro)
                    .addComponent(labelDia)
                    .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMes)
                    .addComponent(ComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAnio)
                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCuantaPuc)
                    .addComponent(txtCuentaPuc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerCodPuc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCodigoKardex)
                    .addComponent(txtCodigoKardex, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarCodigoKardex, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumIdenTercereo)
                    .addComponent(txtNumIdenTercero, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarTercero, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelObservacion)
                    .addComponent(txtObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelValor)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnConsultar)
                    .addComponent(btnModificar))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVolverRegistroIngreso)
                .addContainerGap(89, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverRegistroIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverRegistroIngresoActionPerformed
        // TODO add your handling code here:
        frame.swap(0); // hace el llamado al panel de opciones
    }//GEN-LAST:event_btnVolverRegistroIngresoActionPerformed

    private void btnVerCodPucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCodPucActionPerformed
        // TODO add your handling code here:
         frame.swap(12); // hace el llamado al panel de consultar y seleccionar una cuenta PUC para Ingreso    
    }//GEN-LAST:event_btnVerCodPucActionPerformed

    private void btnConsultarTerceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarTerceroActionPerformed
        // TODO add your handling code here:
        frame.swap(15); // hace el llamado al panel de consultar y seleccionar un tercero para ingreso
    }//GEN-LAST:event_btnConsultarTerceroActionPerformed

    private void btnConsultarCodigoKardexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarCodigoKardexActionPerformed
        // TODO add your handling code here:
        frame.swap(18); // hace el llamado al panel de consultar y seleccionar un kardex(inventario) para ingreso
    }//GEN-LAST:event_btnConsultarCodigoKardexActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxMes;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnConsultarCodigoKardex;
    private javax.swing.JButton btnConsultarTercero;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVerCodPuc;
    private javax.swing.JButton btnVolverRegistroIngreso;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAnio;
    private javax.swing.JLabel labelCodigoKardex;
    private javax.swing.JLabel labelCuantaPuc;
    private javax.swing.JLabel labelDia;
    private javax.swing.JLabel labelFechaRegistro;
    private javax.swing.JLabel labelMes;
    private javax.swing.JLabel labelNumIdenTercereo;
    private javax.swing.JLabel labelObservacion;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelValor;
    private javax.swing.JTable tableRegistroIngreso;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtCodigoKardex;
    private javax.swing.JTextField txtCuentaPuc;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtNumIdenTercero;
    private javax.swing.JTextField txtObservaciones;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
