/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import logica.RegistroCostoLogica;
import modelo.Registrocostos;

/**
 *
 * @author Usuario
 */
public class registroCostoPanel extends javax.swing.JPanel {

    /**
     * Creates new form registroCostoPanel
     */
    vistaPrincipal frame; // instancia frame del frame principal 
    DefaultTableModel modelo;
    private Registrocostos registroCostos;
    private RegistroCostoLogica registroCostoLogica;
    private List<Registrocostos> listaRegistroCostos;
    public registroCostoPanel(vistaPrincipal frame) {
        this.frame = frame; // la instancia del frame principal la paso a una instancia en esta clase para poder usar los metodos del frame principal
        listaRegistroCostos = new ArrayList<Registrocostos>();
        registroCostos = new Registrocostos(); 
        RegistroCostoLogica registroCostoLogica = new RegistroCostoLogica();
        initComponents();
        setBackground(Color.white);
        ComboBoxMes.removeAllItems();
        ComboBoxMes.addItem("ENERO");
        ComboBoxMes.addItem("FEBRERO");
        ComboBoxMes.addItem("MARZO");
        ComboBoxMes.addItem("ABRIL");
        ComboBoxMes.addItem("MAYO");
        ComboBoxMes.addItem("JUNIO");
        ComboBoxMes.addItem("JULIO");
        ComboBoxMes.addItem("AGOSTO");
        ComboBoxMes.addItem("SEPTIEMBRE");
        ComboBoxMes.addItem("OCTUBRE");
        ComboBoxMes.addItem("NOVIEMBRE");
        ComboBoxMes.addItem("DICIEMBRE");
        
        listaRegistroCostos = registroCostoLogica.listarRegistrosCostos();
        llenarTablaGastos(listaRegistroCostos);
        
    }
    
    public void llenarTablaGastos(List<Registrocostos> regcastos){
        
        List<Registrocostos> lista;
        lista = regcastos;
        setTabla(lista);
    }
    
    public void setTabla(List<Registrocostos> regcostos){
        modelo =  (DefaultTableModel) tableCostos.getModel();
        
        int size = modelo.getRowCount();
        for(int i=0; i < size; i++){
            modelo.removeRow(0);
        }
        String aux[];
        for(int j=0;j< regcostos.size();j++){
            aux = new String[9];
            
            aux[0] = String.valueOf(regcostos.get(j).getAnioreg())+"-"+String.valueOf(regcostos.get(j).getMesreg())+"-"+String.valueOf(regcostos.get(j).getDiareg());
            aux[1] = "C-"+String.valueOf(regcostos.get(j).getNumregistro());
            aux[2] = regcostos.get(j).getNumidentificacion();
            aux[3] = regcostos.get(j).getNomtercero();
            aux[4] = regcostos.get(j).getCentrodecostos();
            aux[5] = regcostos.get(j).getCuentapuc();
            aux[6] = regcostos.get(j).getCodigokardex();
            aux[7] = regcostos.get(j).getObservacion();
            aux[8] = "$ "+String.valueOf(regcostos.get(j).getValor());
            modelo.addRow(aux);
        }
    }    
    
    public void setCampoPucSelectCosto(String codigopuc,String nombre){
        txtCuentaPUC.setText(codigopuc+"-"+nombre);
    }
    
    public void setCampoTerceroSelectCosto(int id,String cconit,String nombre){
        txtIDTercero.setText(id+"-"+nombre+"-"+cconit);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        btnVolverRegistroCosto = new javax.swing.JButton();
        labelFechaRegistro = new javax.swing.JLabel();
        labelDiaRegistro = new javax.swing.JLabel();
        txtDia = new javax.swing.JTextField();
        labelMesRegistro = new javax.swing.JLabel();
        ComboBoxMes = new javax.swing.JComboBox<>();
        labelRegistroAnio = new javax.swing.JLabel();
        txtAnio = new javax.swing.JTextField();
        labelCentroCosto = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnConsultaCentroCosto = new javax.swing.JButton();
        labelCuentaPUC = new javax.swing.JLabel();
        txtCuentaPUC = new javax.swing.JTextField();
        btnConsultarPUC = new javax.swing.JButton();
        labelCodigoKardex = new javax.swing.JLabel();
        txtCodigoKardex = new javax.swing.JTextField();
        btnConsultarKardex = new javax.swing.JButton();
        labelObservaciones = new javax.swing.JLabel();
        txtObservaciones = new javax.swing.JTextField();
        labelValor = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCostos = new javax.swing.JTable();
        labelIDTercero = new javax.swing.JLabel();
        txtIDTercero = new javax.swing.JTextField();
        btnConsultarTercero = new javax.swing.JButton();

        labelTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelTitulo.setText("REGISTRO DE COSTOS");

        btnVolverRegistroCosto.setText("Volver");
        btnVolverRegistroCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverRegistroCostoActionPerformed(evt);
            }
        });

        labelFechaRegistro.setText("Fecha de Registro:");

        labelDiaRegistro.setText("Dia:");

        labelMesRegistro.setText("Mes:");

        ComboBoxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        labelRegistroAnio.setText("Año:");

        labelCentroCosto.setText("Centro de Costo:");

        btnConsultaCentroCosto.setText("Consultar Centro Costo");

        labelCuentaPUC.setText("Cuenta PUC:");

        btnConsultarPUC.setText("Consultar PUC");
        btnConsultarPUC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarPUCActionPerformed(evt);
            }
        });

        labelCodigoKardex.setText("Codigo Kardex:");

        btnConsultarKardex.setText("Consultar Kardex");
        btnConsultarKardex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarKardexActionPerformed(evt);
            }
        });

        labelObservaciones.setText("Observaciones:");

        labelValor.setText("Valor:");

        btnRegistrar.setText("Registrar");

        btnConsultar.setText("Consultar");

        jButton1.setText("Modificar");

        tableCostos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "N° Registro", "N° Identificacion", "Nombre", "Centro Costo", "Cuenta PUC", "Codigo Kardex", "Observaciones ", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableCostos);

        labelIDTercero.setText("ID Tercero:");

        btnConsultarTercero.setText("Consultar Tercero");
        btnConsultarTercero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarTerceroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTitulo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelCentroCosto)
                            .addComponent(labelFechaRegistro)
                            .addComponent(labelCodigoKardex))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelDiaRegistro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelMesRegistro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelRegistroAnio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCodigoKardex, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnConsultarKardex)
                                .addGap(18, 18, 18)
                                .addComponent(labelIDTercero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIDTercero, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnConsultarTercero, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnConsultaCentroCosto)
                                .addGap(18, 18, 18)
                                .addComponent(labelCuentaPUC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCuentaPUC, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnConsultarPUC))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRegistrar)
                            .addComponent(labelObservaciones))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelValor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(btnConsultar)
                                .addGap(28, 28, 28)
                                .addComponent(jButton1))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnVolverRegistroCosto)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(labelTitulo)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFechaRegistro)
                    .addComponent(labelDiaRegistro)
                    .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMesRegistro)
                    .addComponent(ComboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRegistroAnio)
                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCentroCosto)
                    .addComponent(btnConsultaCentroCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCuentaPUC)
                    .addComponent(txtCuentaPUC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarPUC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCodigoKardex)
                    .addComponent(txtCodigoKardex, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarKardex, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIDTercero)
                    .addComponent(txtIDTercero, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarTercero, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelObservaciones)
                    .addComponent(txtObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelValor)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVolverRegistroCosto)
                .addContainerGap(114, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverRegistroCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverRegistroCostoActionPerformed
        // TODO add your handling code here:
        frame.swap(0); // hace el llamado al panel de opciones
    }//GEN-LAST:event_btnVolverRegistroCostoActionPerformed

    private void btnConsultarPUCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPUCActionPerformed
        // TODO add your handling code here:
        frame.swap(13); // hace el llamado al panel de consultar y seleccionar una cuenta PUC para costo
    }//GEN-LAST:event_btnConsultarPUCActionPerformed

    private void btnConsultarTerceroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarTerceroActionPerformed
        // TODO add your handling code here:
        frame.swap(16); // hace el llamado al panel de consultar y seleccionar un tercero para costo
    }//GEN-LAST:event_btnConsultarTerceroActionPerformed

    private void btnConsultarKardexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarKardexActionPerformed
        // TODO add your handling code here:
        frame.swap(19); // hace el llamado al panel de consultar y seleccionar un Kardex(Inventario) para costo
    }//GEN-LAST:event_btnConsultarKardexActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxMes;
    private javax.swing.JButton btnConsultaCentroCosto;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnConsultarKardex;
    private javax.swing.JButton btnConsultarPUC;
    private javax.swing.JButton btnConsultarTercero;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVolverRegistroCosto;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelCentroCosto;
    private javax.swing.JLabel labelCodigoKardex;
    private javax.swing.JLabel labelCuentaPUC;
    private javax.swing.JLabel labelDiaRegistro;
    private javax.swing.JLabel labelFechaRegistro;
    private javax.swing.JLabel labelIDTercero;
    private javax.swing.JLabel labelMesRegistro;
    private javax.swing.JLabel labelObservaciones;
    private javax.swing.JLabel labelRegistroAnio;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelValor;
    private javax.swing.JTable tableCostos;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtCodigoKardex;
    private javax.swing.JTextField txtCuentaPUC;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtIDTercero;
    private javax.swing.JTextField txtObservaciones;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
