/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JPanel;

/**
 *
 * @author Jhon
 */
public class vistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form vistaPrincipal
     */
    JPanel panels[] = new JPanel[9]; // ir incrementando el valor de este arreglo en la medida que se van creando los paneles
    
    public vistaPrincipal() {
        
        opcionesPanel panelOpciones = new opcionesPanel(this); 
        panelOpciones.setBounds(0, 0, 900, 650);
        setResizable(false); // esto evita que el frame cambie de tamaño
        agregarPanel(0,panelOpciones); // Panel 0 - Panel Registro de ingresos
        panelOpciones.setVisible(true);
        ////////////////////
        
        registroIngresoPanel panelRegistroIngreso = new registroIngresoPanel(this); 
        panelRegistroIngreso.setBounds(0, 0, 900, 650);
        agregarPanel(1,panelRegistroIngreso); // Panel 1 - Panel Registro de ingresos
        panelRegistroIngreso.setVisible(false);
        ////////////////////
        
        registroCostoPanel panelRegistroCosto = new registroCostoPanel(this); 
        panelRegistroCosto.setBounds(0, 0, 900, 650);
        agregarPanel(2,panelRegistroCosto); // Panel 2 - Panel Registro de costo
        panelRegistroCosto.setVisible(false);
        ////////////////////
        
        registroGastoPanel panelRegistroGasto = new registroGastoPanel(this); 
        panelRegistroGasto.setBounds(0, 0, 900, 650);
        agregarPanel(3,panelRegistroGasto); // Panel 3 - Panel Registro de gastos
        panelRegistroGasto.setVisible(false);
        ////////////////////
        
        entradaSalidaPanel panelESInventario = new entradaSalidaPanel(this); 
        panelESInventario.setBounds(0, 0, 900, 650);
        agregarPanel(4,panelESInventario); // Panel 4 - Panel Entrada/Salida Inventarios
        panelESInventario.setVisible(false);
        ////////////////////
        
        consultasPanel panelConsultas = new consultasPanel(this); 
        panelConsultas.setBounds(0, 0, 900, 650);
        agregarPanel(5,panelConsultas); // Panel 5 - Panel Consultas
        panelConsultas.setVisible(false);
        ////////////////////
        
        consultaCuentasPUCPanel panelConsultaCuentasPUCPanel = new consultaCuentasPUCPanel(this); 
        panelConsultaCuentasPUCPanel.setBounds(0, 0, 900, 650);
        agregarPanel(6,panelConsultaCuentasPUCPanel); // Panel 6 - Panel Consultas
        panelConsultaCuentasPUCPanel.setVisible(false);
        ////////////////////
        consultaCentroCostoPanel panelConsultaCentroCosto = new consultaCentroCostoPanel(this); 
        panelConsultaCentroCosto.setBounds(0, 0, 900, 650);
        agregarPanel(7,panelConsultaCentroCosto); // Panel 7 - Panel Consultas
        panelConsultaCentroCosto.setVisible(false);
        ////////////////////
        consultaReporteEstadoResultados panelResporteEstadoResultados = new consultaReporteEstadoResultados(this); 
        panelResporteEstadoResultados.setBounds(0, 0, 900, 650);
        agregarPanel(8,panelResporteEstadoResultados); // Panel 8 - Panel Reporte Estados de Resultados
        panelResporteEstadoResultados.setVisible(false);
        
        this.add(panelOpciones);
        this.add(panelRegistroIngreso);
        this.add(panelRegistroCosto);
        this.add(panelRegistroGasto);
        this.add(panelESInventario);
        this.add(panelConsultas);
        this.add(panelConsultaCuentasPUCPanel);
        this.add(panelConsultaCentroCosto);
        this.add(panelResporteEstadoResultados);
        initComponents();
    }
    
    //En este metodo realizo el intercambio de paneles dejanso visible el panel de interes
    // indicado por el entero n, y ocultando los demas paneles que no son de interes
    public void swap(int n){
        for(int i=0; i < panels.length; i++){
            panels[i].setVisible(false);
        }
        panels[n].setVisible(true);
    } 
    
    // Agrego los paneles que he creado a un arreglo de paneles, con esto es posible
    // hacer de manera facil el intercambio entre paneles, con el metodo swap 
    // se realiza el intercambio de paneles depues de haberlo agrado al arreglo
    public void agregarPanel(int n, JPanel panel){
        panels[n] = panel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA DE GESTION CONTABLE");
        setPreferredSize(new java.awt.Dimension(900, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
