/* TABLA QUE ALMACENA LOS CODIGOS DEL CENTRO DE COSTOS*/
CREATE TABLE IF NOT EXISTS centrodecostos (
	codigo VARCHAR(11) NOT NULL,
	nombre VARCHAR(50) NOT NULL,
	PRIMARY KEY (codigo)
);

/* TABLA QUE ALMACENA LOS CODIGO PUC COMPLETOS*/
CREATE TABLE IF NOT EXISTS puc (
	codigo VARCHAR(11) NOT NULL,
	nombre VARCHAR(1000) NOT NULL,
	PRIMARY KEY (codigo)
);

/* TABLA QUE ALMACENA LOS CODIGO PUC QUE COMIENZAN POR 4 QUE HACEN REFERENCIA A INGRESOS */
CREATE TABLE IF NOT EXISTS puccuatroingresos (
	codigo VARCHAR(11) NOT NULL,
	nombre VARCHAR(1000) NOT NULL,
	PRIMARY KEY (codigo)
);

/* TABLA QUE ALMACENA LOS CODIGO PUC QUE COMIENZAN POR 5 QUE HACEN REFERENCIA A GASTOS */
CREATE TABLE IF NOT EXISTS puccincogastos (
	codigo VARCHAR(11) NOT NULL,
	nombre VARCHAR(1000) NOT NULL,
	PRIMARY KEY (codigo)
);

/* TABLA QUE ALMACENA LOS CODIGO PUC QUE COMIENZAN POR 6 QUE HACEN REFERENCIA A COSTOS */
CREATE TABLE IF NOT EXISTS pucseiscostos (
	codigo VARCHAR(11) NOT NULL,
	nombre VARCHAR(1000) NOT NULL,
	PRIMARY KEY (codigo)
);

/* TABLA QUE ALMACENA EL INVENTARIO MAESTRO COMPLETO */
CREATE TABLE IF NOT EXISTS maestroinventariocompleto (
	codigo VARCHAR(11) NOT NULL,
	descripcion VARCHAR(1000) NOT NULL,
	PRIMARY KEY (codigo)
);

/* TABLA QUE ALMACENA LA PARTE 3 DEL INVENTARIO MAESTRO QUE HACE REFERENCIA A LOS PRODUCTOS TERMINADOS*/
CREATE TABLE IF NOT EXISTS maestroinventariotrespt (
	codigo VARCHAR(11) NOT NULL,
	descripcion VARCHAR(1000) NOT NULL,
	PRIMARY KEY (codigo)
);

/* TABLA QUE ALMACENA LA PARTE 2 DEL INVENTARIO MAESTRO QUE HACE REFERENCIA A LOS PRODUCTOS EN PROCESO */
CREATE TABLE IF NOT EXISTS maestroinventariodospp (
	codigo VARCHAR(11) NOT NULL,
	descripcion VARCHAR(1000) NOT NULL,
	PRIMARY KEY (codigo)
);

/* TABLA QUE ALMACENA LA PARTE 1 DEL INVENTARIO MAESTRO QUE HACE REFERENCIA A LOS MATERIALES E INSUMOS */
CREATE TABLE IF NOT EXISTS maestroinventariounomi (
	codigo VARCHAR(11) NOT NULL,
	descripcion VARCHAR(1000) NOT NULL,
	PRIMARY KEY (codigo)
);

/* TABLA QUE ALMACENA LA BASE DE DATOS DE TERCEROS */
CREATE TABLE IF NOT EXISTS listadoterceros (
	cconit VARCHAR(20) NOT NULL,
	tipo VARCHAR(50) NOT NULL,
	nombre VARCHAR(500) NOT NULL,
  direccion VARCHAR(500) NOT NULL,
	telefono VARCHAR(50) NOT NULL,
	PRIMARY KEY (cconit)
);

CREATE TABLE IF NOT EXISTS registroingresos (
	numregistro SERIAL NOT NULL,
	anioreg INTEGER(10) NOT NULL,
	mesreg INTEGER(10) NOT NULL,
	diareg INTEGER(10) NOT NULL,
	cconit VARCHAR(20) NOT NULL,
	nomtercero VARCHAR(500) NOT NULL,
	cuentapuc VARCHAR(11) NOT NULL,
	codigokardex VARCHAR(11) NOT NULL,
	observacion VARCHAR(11),
	valor INTEGER(11) NOT NULL,
	PRIMARY KEY (numregistro)
);

CREATE TABLE IF NOT EXISTS registrocostos (
	numregistro SERIAL NOT NULL,
	anioreg INTEGER(10) NOT NULL,
	mesreg INTEGER(10) NOT NULL,
	diareg INTEGER(10) NOT NULL,
	cconit VARCHAR(20) NOT NULL,
	nomtercero VARCHAR(500) NOT NULL,
	cuentapuc VARCHAR(11) NOT NULL,
	codigokardex VARCHAR(11) NOT NULL,
	observacion VARCHAR(11),
	valor INTEGER(11) NOT NULL,
	PRIMARY KEY (numregistro)
);
