/* TABLA QUE ALMACENA LOS CODIGOS DEL CENTRO DE COSTOS*/
CREATE TABLE IF NOT EXISTS centrodecostos (
	codigo VARCHAR(20) NOT NULL,
	nombre VARCHAR(50) NOT NULL,
	PRIMARY KEY (codigo)
);

/* TABLA QUE ALMACENA LOS CODIGO PUC COMPLETOS*/
CREATE TABLE IF NOT EXISTS puc (
	codigo VARCHAR(20) NOT NULL,
	nombre VARCHAR(1000) NOT NULL,
	PRIMARY KEY (codigo)
);

/* TABLA QUE ALMACENA LOS CODIGO PUC QUE COMIENZAN POR 4 QUE HACEN REFERENCIA A INGRESOS */
CREATE TABLE IF NOT EXISTS puccuatroingresos (
	codigo VARCHAR(20) NOT NULL,
	nombre VARCHAR(1000) NOT NULL,
	PRIMARY KEY (codigo)
);

/* TABLA QUE ALMACENA LOS CODIGO PUC QUE COMIENZAN POR 5 QUE HACEN REFERENCIA A GASTOS */
CREATE TABLE IF NOT EXISTS puccincogastos (
	codigo VARCHAR(20) NOT NULL,
	nombre VARCHAR(1000) NOT NULL,
	PRIMARY KEY (codigo)
);

/* TABLA QUE ALMACENA LOS CODIGO PUC QUE COMIENZAN POR 6 QUE HACEN REFERENCIA A COSTOS */
CREATE TABLE IF NOT EXISTS pucseiscostos (
	codigo VARCHAR(20) NOT NULL,
	nombre VARCHAR(1000) NOT NULL,
	PRIMARY KEY (codigo)
);

/* TABLA QUE ALMACENA EL INVENTARIO MAESTRO COMPLETO */
CREATE TABLE IF NOT EXISTS maestroinventariocompleto (
	codigo VARCHAR(20) NOT NULL,
	descripcion VARCHAR(1000) NOT NULL,
	PRIMARY KEY (codigo)
);

/* TABLA QUE ALMACENA LA PARTE 3 DEL INVENTARIO MAESTRO QUE HACE REFERENCIA A LOS PRODUCTOS TERMINADOS*/
CREATE TABLE IF NOT EXISTS maestroinventariotrespt (
	codigo VARCHAR(20) NOT NULL,
	descripcion VARCHAR(1000) NOT NULL,
	PRIMARY KEY (codigo)
);

/* TABLA QUE ALMACENA LA PARTE 2 DEL INVENTARIO MAESTRO QUE HACE REFERENCIA A LOS PRODUCTOS EN PROCESO */
CREATE TABLE IF NOT EXISTS maestroinventariodospp (
	codigo VARCHAR(20) NOT NULL,
	descripcion VARCHAR(1000) NOT NULL,
	PRIMARY KEY (codigo)
);

/* TABLA QUE ALMACENA LA PARTE 1 DEL INVENTARIO MAESTRO QUE HACE REFERENCIA A LOS MATERIALES E INSUMOS */
CREATE TABLE IF NOT EXISTS maestroinventariounomi (
	codigo VARCHAR(20) NOT NULL,
	descripcion VARCHAR(1000) NOT NULL,
	PRIMARY KEY (codigo)
);

/* TABLA QUE ALMACENA LA BASE DE DATOS DE TERCEROS */
CREATE TABLE IF NOT EXISTS listadoterceros (
	id SERIAL NOT NULL,
	tipo VARCHAR(50) NOT NULL,
	cconit VARCHAR(20),
	nombre VARCHAR(500),
  direccion VARCHAR(500),
	telefono VARCHAR(50),
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS registroingresos (
	numregistro SERIAL NOT NULL,
	anioreg INTEGER(10),
	mesreg INTEGER(10),
	diareg INTEGER(10),
	numidentificacion VARCHAR(20),
	nomtercero VARCHAR(500),
	cuentapuc VARCHAR(11),
	codigokardex VARCHAR(11),
	observacion VARCHAR(1000),
	valor INTEGER(11) NOT NULL,
	PRIMARY KEY (numregistro)
);

CREATE TABLE IF NOT EXISTS registrogastos (
	numregistro SERIAL NOT NULL,
	anioreg INTEGER(10),
	mesreg INTEGER(10),
	diareg INTEGER(10),
	numidentificacion VARCHAR(20),
	nomtercero VARCHAR(500),
	centrodecostos VARCHAR(20),
	cuentapuc VARCHAR(11),
	observacion VARCHAR(1000),
	valor INTEGER(11) NOT NULL,
	PRIMARY KEY (numregistro)
);

CREATE TABLE IF NOT EXISTS registrocostos (
	numregistro SERIAL NOT NULL,
	anioreg INTEGER(10) NOT NULL,
	mesreg INTEGER(10) NOT NULL,
	diareg INTEGER(10) NOT NULL,
	numidentificacion VARCHAR(20),
	nomtercero VARCHAR(500),
	centrodecostos VARCHAR(20),
	cuentapuc VARCHAR(11),
	codigokardex VARCHAR(11),
	observacion VARCHAR(1000),
	valor INTEGER(11) NOT NULL,
	PRIMARY KEY (numregistro)
);

CREATE TABLE IF NOT EXISTS listadocostounitario (
	codigokardex VARCHAR(11),
	costounitario INTEGER(11) NOT NULL,
	PRIMARY KEY (codigokardex)
);
